### ISSUE TITLE
Add timestamps to comments in Review and Approval Panel 

### ISSUE THREAD

**Issue by vantuyls** [osulp/Scholars-Archive#1494]
I would prefer we do this on Hyrax

https://github.com/samvera/hyrax/issues/3125

**Comment by straleyb** [comment]
Verify this is fixed in SA

**Comment by straleyb** [comment]
https://github.com/samvera/hyrax/pull/3224 Fixed by

**Comment by CGillen** [comment]
Not actually fixed. Wrong ticket was tagged in Hyrax PR.
Can easily prepend `#created_at` here: https://github.com/osulp/Scholars-Archive/blob/master/app/views/hyrax/base/_workflow_actions.html.erb#L35

**Comment by lamtu1** [comment]
Fixed by PR #2418 & #2411
