### ISSUE TITLE
Empty fields & no editing

### ISSUE THREAD

**Issue by simholt** [osulp/Scholars-Archive#1768]
Encountered child items with empty contributor fields -- that should not be empty. Clicking the edit button goes to the ack broken message.

![screen shot 2018-11-08 at 10 45 41 am](https://user-images.githubusercontent.com/33705514/48220180-77619d00-e343-11e8-9caa-a1396a08ef4e.png)

I looked the problem item ids up in Solr and they have `nested_ordered_contributor` fields but no `contributor`. 

Problem items (there are others):
https://ir.library.oregonstate.edu/concern/technical_reports/2j62sb089
https://ir.library.oregonstate.edu/concern/technical_reports/j3860c75r
https://ir.library.oregonstate.edu/concern/technical_reports/8910k043q
https://ir.library.oregonstate.edu/concern/technical_reports/qv33s275m

Related: #1763

**Comment by luisgreg99** [comment]
It looks like this issue is related to https://github.com/osulp/Scholars-Archive/issues/1728 We had a similar issue with `creator` and `title`. 

I have compiled a list of works in this spreadsheet where I will be updating the migration status: https://docs.google.com/spreadsheets/d/13KT0IpDcjzqJu_IC3kLO_smaFpqzN2csRp_21i4Gz0c/edit#gid=1235297103 

Found 28 works missing contributors and 49 works missing additional informations. I will tweak the rake task used for creator to cleanup these works.

**Comment by vantuyls** [comment]
@simholt @luisgreg99 can either of you confirm that this is resolved?

**Comment by simholt** [comment]
I still encounter these occasionally - will see if I can dig up some examples.

**Comment by simholt** [comment]
I think we can close this for now - I will keep my eyes open for others.
